version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - yarn install
      - npx puppeteer browsers install chrome

  build:
    commands:
      - yarn build

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
