version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - sudo amazon-linux-extras install epel -y
      - sudo yum install -y chromium
      - yarn install

  build:
    commands:
      - yarn build

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
